/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PerfilIndexRouteImport } from './routes/perfil/index'
import { Route as OrgIndexRouteImport } from './routes/org/index'
import { Route as MiPerfilIndexRouteImport } from './routes/mi-perfil/index'
import { Route as EventosIndexRouteImport } from './routes/eventos/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as InscripcionEventIdRouteImport } from './routes/inscripcion/$eventId'
import { Route as EventosSlugRouteImport } from './routes/eventos/$slug'
import { Route as ConfirmacionRegistrationIdRouteImport } from './routes/confirmacion/$registrationId'
import { Route as CheckoutOrderIdRouteImport } from './routes/checkout/$orderId'
import { Route as AuthRegistroRouteImport } from './routes/auth/registro'
import { Route as AuthRecuperarRouteImport } from './routes/auth/recuperar'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminAptosRouteImport } from './routes/admin/aptos'
import { Route as OrgEventosIndexRouteImport } from './routes/org/eventos/index'
import { Route as OrgAddonsIndexRouteImport } from './routes/org/addons/index'
import { Route as AdminOrganizacionesIndexRouteImport } from './routes/admin/organizaciones/index'
import { Route as AdminInscripcionesIndexRouteImport } from './routes/admin/inscripciones/index'
import { Route as AdminEventosIndexRouteImport } from './routes/admin/eventos/index'
import { Route as OrgEventosNuevoRouteImport } from './routes/org/eventos/nuevo'
import { Route as AdminOrganizacionesNuevaRouteImport } from './routes/admin/organizaciones/nueva'
import { Route as AdminInscripcionesEventIdRouteImport } from './routes/admin/inscripciones/$eventId'
import { Route as AdminEventosNuevoRouteImport } from './routes/admin/eventos/nuevo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilIndexRoute = PerfilIndexRouteImport.update({
  id: '/perfil/',
  path: '/perfil/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgIndexRoute = OrgIndexRouteImport.update({
  id: '/org/',
  path: '/org/',
  getParentRoute: () => rootRouteImport,
} as any)
const MiPerfilIndexRoute = MiPerfilIndexRouteImport.update({
  id: '/mi-perfil/',
  path: '/mi-perfil/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosIndexRoute = EventosIndexRouteImport.update({
  id: '/eventos/',
  path: '/eventos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const InscripcionEventIdRoute = InscripcionEventIdRouteImport.update({
  id: '/inscripcion/$eventId',
  path: '/inscripcion/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosSlugRoute = EventosSlugRouteImport.update({
  id: '/eventos/$slug',
  path: '/eventos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmacionRegistrationIdRoute =
  ConfirmacionRegistrationIdRouteImport.update({
    id: '/confirmacion/$registrationId',
    path: '/confirmacion/$registrationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CheckoutOrderIdRoute = CheckoutOrderIdRouteImport.update({
  id: '/checkout/$orderId',
  path: '/checkout/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegistroRoute = AuthRegistroRouteImport.update({
  id: '/auth/registro',
  path: '/auth/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRecuperarRoute = AuthRecuperarRouteImport.update({
  id: '/auth/recuperar',
  path: '/auth/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAptosRoute = AdminAptosRouteImport.update({
  id: '/admin/aptos',
  path: '/admin/aptos',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgEventosIndexRoute = OrgEventosIndexRouteImport.update({
  id: '/org/eventos/',
  path: '/org/eventos/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgAddonsIndexRoute = OrgAddonsIndexRouteImport.update({
  id: '/org/addons/',
  path: '/org/addons/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizacionesIndexRoute =
  AdminOrganizacionesIndexRouteImport.update({
    id: '/admin/organizaciones/',
    path: '/admin/organizaciones/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminInscripcionesIndexRoute = AdminInscripcionesIndexRouteImport.update({
  id: '/admin/inscripciones/',
  path: '/admin/inscripciones/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventosIndexRoute = AdminEventosIndexRouteImport.update({
  id: '/admin/eventos/',
  path: '/admin/eventos/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgEventosNuevoRoute = OrgEventosNuevoRouteImport.update({
  id: '/org/eventos/nuevo',
  path: '/org/eventos/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizacionesNuevaRoute =
  AdminOrganizacionesNuevaRouteImport.update({
    id: '/admin/organizaciones/nueva',
    path: '/admin/organizaciones/nueva',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminInscripcionesEventIdRoute =
  AdminInscripcionesEventIdRouteImport.update({
    id: '/admin/inscripciones/$eventId',
    path: '/admin/inscripciones/$eventId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminEventosNuevoRoute = AdminEventosNuevoRouteImport.update({
  id: '/admin/eventos/nuevo',
  path: '/admin/eventos/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/aptos': typeof AdminAptosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recuperar': typeof AuthRecuperarRoute
  '/auth/registro': typeof AuthRegistroRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/confirmacion/$registrationId': typeof ConfirmacionRegistrationIdRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/inscripcion/$eventId': typeof InscripcionEventIdRoute
  '/admin/': typeof AdminIndexRoute
  '/eventos/': typeof EventosIndexRoute
  '/mi-perfil/': typeof MiPerfilIndexRoute
  '/org/': typeof OrgIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/admin/eventos/nuevo': typeof AdminEventosNuevoRoute
  '/admin/inscripciones/$eventId': typeof AdminInscripcionesEventIdRoute
  '/admin/organizaciones/nueva': typeof AdminOrganizacionesNuevaRoute
  '/org/eventos/nuevo': typeof OrgEventosNuevoRoute
  '/admin/eventos/': typeof AdminEventosIndexRoute
  '/admin/inscripciones/': typeof AdminInscripcionesIndexRoute
  '/admin/organizaciones/': typeof AdminOrganizacionesIndexRoute
  '/org/addons/': typeof OrgAddonsIndexRoute
  '/org/eventos/': typeof OrgEventosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/aptos': typeof AdminAptosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recuperar': typeof AuthRecuperarRoute
  '/auth/registro': typeof AuthRegistroRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/confirmacion/$registrationId': typeof ConfirmacionRegistrationIdRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/inscripcion/$eventId': typeof InscripcionEventIdRoute
  '/admin': typeof AdminIndexRoute
  '/eventos': typeof EventosIndexRoute
  '/mi-perfil': typeof MiPerfilIndexRoute
  '/org': typeof OrgIndexRoute
  '/perfil': typeof PerfilIndexRoute
  '/admin/eventos/nuevo': typeof AdminEventosNuevoRoute
  '/admin/inscripciones/$eventId': typeof AdminInscripcionesEventIdRoute
  '/admin/organizaciones/nueva': typeof AdminOrganizacionesNuevaRoute
  '/org/eventos/nuevo': typeof OrgEventosNuevoRoute
  '/admin/eventos': typeof AdminEventosIndexRoute
  '/admin/inscripciones': typeof AdminInscripcionesIndexRoute
  '/admin/organizaciones': typeof AdminOrganizacionesIndexRoute
  '/org/addons': typeof OrgAddonsIndexRoute
  '/org/eventos': typeof OrgEventosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/aptos': typeof AdminAptosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recuperar': typeof AuthRecuperarRoute
  '/auth/registro': typeof AuthRegistroRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/confirmacion/$registrationId': typeof ConfirmacionRegistrationIdRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/inscripcion/$eventId': typeof InscripcionEventIdRoute
  '/admin/': typeof AdminIndexRoute
  '/eventos/': typeof EventosIndexRoute
  '/mi-perfil/': typeof MiPerfilIndexRoute
  '/org/': typeof OrgIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/admin/eventos/nuevo': typeof AdminEventosNuevoRoute
  '/admin/inscripciones/$eventId': typeof AdminInscripcionesEventIdRoute
  '/admin/organizaciones/nueva': typeof AdminOrganizacionesNuevaRoute
  '/org/eventos/nuevo': typeof OrgEventosNuevoRoute
  '/admin/eventos/': typeof AdminEventosIndexRoute
  '/admin/inscripciones/': typeof AdminInscripcionesIndexRoute
  '/admin/organizaciones/': typeof AdminOrganizacionesIndexRoute
  '/org/addons/': typeof OrgAddonsIndexRoute
  '/org/eventos/': typeof OrgEventosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/aptos'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/recuperar'
    | '/auth/registro'
    | '/checkout/$orderId'
    | '/confirmacion/$registrationId'
    | '/eventos/$slug'
    | '/inscripcion/$eventId'
    | '/admin/'
    | '/eventos/'
    | '/mi-perfil/'
    | '/org/'
    | '/perfil/'
    | '/admin/eventos/nuevo'
    | '/admin/inscripciones/$eventId'
    | '/admin/organizaciones/nueva'
    | '/org/eventos/nuevo'
    | '/admin/eventos/'
    | '/admin/inscripciones/'
    | '/admin/organizaciones/'
    | '/org/addons/'
    | '/org/eventos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/aptos'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/recuperar'
    | '/auth/registro'
    | '/checkout/$orderId'
    | '/confirmacion/$registrationId'
    | '/eventos/$slug'
    | '/inscripcion/$eventId'
    | '/admin'
    | '/eventos'
    | '/mi-perfil'
    | '/org'
    | '/perfil'
    | '/admin/eventos/nuevo'
    | '/admin/inscripciones/$eventId'
    | '/admin/organizaciones/nueva'
    | '/org/eventos/nuevo'
    | '/admin/eventos'
    | '/admin/inscripciones'
    | '/admin/organizaciones'
    | '/org/addons'
    | '/org/eventos'
  id:
    | '__root__'
    | '/'
    | '/admin/aptos'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/recuperar'
    | '/auth/registro'
    | '/checkout/$orderId'
    | '/confirmacion/$registrationId'
    | '/eventos/$slug'
    | '/inscripcion/$eventId'
    | '/admin/'
    | '/eventos/'
    | '/mi-perfil/'
    | '/org/'
    | '/perfil/'
    | '/admin/eventos/nuevo'
    | '/admin/inscripciones/$eventId'
    | '/admin/organizaciones/nueva'
    | '/org/eventos/nuevo'
    | '/admin/eventos/'
    | '/admin/inscripciones/'
    | '/admin/organizaciones/'
    | '/org/addons/'
    | '/org/eventos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAptosRoute: typeof AdminAptosRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRecuperarRoute: typeof AuthRecuperarRoute
  AuthRegistroRoute: typeof AuthRegistroRoute
  CheckoutOrderIdRoute: typeof CheckoutOrderIdRoute
  ConfirmacionRegistrationIdRoute: typeof ConfirmacionRegistrationIdRoute
  EventosSlugRoute: typeof EventosSlugRoute
  InscripcionEventIdRoute: typeof InscripcionEventIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  EventosIndexRoute: typeof EventosIndexRoute
  MiPerfilIndexRoute: typeof MiPerfilIndexRoute
  OrgIndexRoute: typeof OrgIndexRoute
  PerfilIndexRoute: typeof PerfilIndexRoute
  AdminEventosNuevoRoute: typeof AdminEventosNuevoRoute
  AdminInscripcionesEventIdRoute: typeof AdminInscripcionesEventIdRoute
  AdminOrganizacionesNuevaRoute: typeof AdminOrganizacionesNuevaRoute
  OrgEventosNuevoRoute: typeof OrgEventosNuevoRoute
  AdminEventosIndexRoute: typeof AdminEventosIndexRoute
  AdminInscripcionesIndexRoute: typeof AdminInscripcionesIndexRoute
  AdminOrganizacionesIndexRoute: typeof AdminOrganizacionesIndexRoute
  OrgAddonsIndexRoute: typeof OrgAddonsIndexRoute
  OrgEventosIndexRoute: typeof OrgEventosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/': {
      id: '/perfil/'
      path: '/perfil'
      fullPath: '/perfil/'
      preLoaderRoute: typeof PerfilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/': {
      id: '/org/'
      path: '/org'
      fullPath: '/org/'
      preLoaderRoute: typeof OrgIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-perfil/': {
      id: '/mi-perfil/'
      path: '/mi-perfil'
      fullPath: '/mi-perfil/'
      preLoaderRoute: typeof MiPerfilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/': {
      id: '/eventos/'
      path: '/eventos'
      fullPath: '/eventos/'
      preLoaderRoute: typeof EventosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscripcion/$eventId': {
      id: '/inscripcion/$eventId'
      path: '/inscripcion/$eventId'
      fullPath: '/inscripcion/$eventId'
      preLoaderRoute: typeof InscripcionEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/$slug': {
      id: '/eventos/$slug'
      path: '/eventos/$slug'
      fullPath: '/eventos/$slug'
      preLoaderRoute: typeof EventosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmacion/$registrationId': {
      id: '/confirmacion/$registrationId'
      path: '/confirmacion/$registrationId'
      fullPath: '/confirmacion/$registrationId'
      preLoaderRoute: typeof ConfirmacionRegistrationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$orderId': {
      id: '/checkout/$orderId'
      path: '/checkout/$orderId'
      fullPath: '/checkout/$orderId'
      preLoaderRoute: typeof CheckoutOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/registro': {
      id: '/auth/registro'
      path: '/auth/registro'
      fullPath: '/auth/registro'
      preLoaderRoute: typeof AuthRegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/recuperar': {
      id: '/auth/recuperar'
      path: '/auth/recuperar'
      fullPath: '/auth/recuperar'
      preLoaderRoute: typeof AuthRecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/aptos': {
      id: '/admin/aptos'
      path: '/admin/aptos'
      fullPath: '/admin/aptos'
      preLoaderRoute: typeof AdminAptosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/eventos/': {
      id: '/org/eventos/'
      path: '/org/eventos'
      fullPath: '/org/eventos/'
      preLoaderRoute: typeof OrgEventosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/addons/': {
      id: '/org/addons/'
      path: '/org/addons'
      fullPath: '/org/addons/'
      preLoaderRoute: typeof OrgAddonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organizaciones/': {
      id: '/admin/organizaciones/'
      path: '/admin/organizaciones'
      fullPath: '/admin/organizaciones/'
      preLoaderRoute: typeof AdminOrganizacionesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inscripciones/': {
      id: '/admin/inscripciones/'
      path: '/admin/inscripciones'
      fullPath: '/admin/inscripciones/'
      preLoaderRoute: typeof AdminInscripcionesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/eventos/': {
      id: '/admin/eventos/'
      path: '/admin/eventos'
      fullPath: '/admin/eventos/'
      preLoaderRoute: typeof AdminEventosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/eventos/nuevo': {
      id: '/org/eventos/nuevo'
      path: '/org/eventos/nuevo'
      fullPath: '/org/eventos/nuevo'
      preLoaderRoute: typeof OrgEventosNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organizaciones/nueva': {
      id: '/admin/organizaciones/nueva'
      path: '/admin/organizaciones/nueva'
      fullPath: '/admin/organizaciones/nueva'
      preLoaderRoute: typeof AdminOrganizacionesNuevaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inscripciones/$eventId': {
      id: '/admin/inscripciones/$eventId'
      path: '/admin/inscripciones/$eventId'
      fullPath: '/admin/inscripciones/$eventId'
      preLoaderRoute: typeof AdminInscripcionesEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/eventos/nuevo': {
      id: '/admin/eventos/nuevo'
      path: '/admin/eventos/nuevo'
      fullPath: '/admin/eventos/nuevo'
      preLoaderRoute: typeof AdminEventosNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAptosRoute: AdminAptosRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRecuperarRoute: AuthRecuperarRoute,
  AuthRegistroRoute: AuthRegistroRoute,
  CheckoutOrderIdRoute: CheckoutOrderIdRoute,
  ConfirmacionRegistrationIdRoute: ConfirmacionRegistrationIdRoute,
  EventosSlugRoute: EventosSlugRoute,
  InscripcionEventIdRoute: InscripcionEventIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  EventosIndexRoute: EventosIndexRoute,
  MiPerfilIndexRoute: MiPerfilIndexRoute,
  OrgIndexRoute: OrgIndexRoute,
  PerfilIndexRoute: PerfilIndexRoute,
  AdminEventosNuevoRoute: AdminEventosNuevoRoute,
  AdminInscripcionesEventIdRoute: AdminInscripcionesEventIdRoute,
  AdminOrganizacionesNuevaRoute: AdminOrganizacionesNuevaRoute,
  OrgEventosNuevoRoute: OrgEventosNuevoRoute,
  AdminEventosIndexRoute: AdminEventosIndexRoute,
  AdminInscripcionesIndexRoute: AdminInscripcionesIndexRoute,
  AdminOrganizacionesIndexRoute: AdminOrganizacionesIndexRoute,
  OrgAddonsIndexRoute: OrgAddonsIndexRoute,
  OrgEventosIndexRoute: OrgEventosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
