/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MiPerfilIndexRouteImport } from './routes/mi-perfil/index'
import { Route as EventosIndexRouteImport } from './routes/eventos/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as InscripcionEventIdRouteImport } from './routes/inscripcion/$eventId'
import { Route as EventosSlugRouteImport } from './routes/eventos/$slug'
import { Route as ConfirmacionRegistrationIdRouteImport } from './routes/confirmacion/$registrationId'
import { Route as CheckoutOrderIdRouteImport } from './routes/checkout/$orderId'
import { Route as AuthRegistroRouteImport } from './routes/auth/registro'
import { Route as AuthRecuperarRouteImport } from './routes/auth/recuperar'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MiPerfilIndexRoute = MiPerfilIndexRouteImport.update({
  id: '/mi-perfil/',
  path: '/mi-perfil/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosIndexRoute = EventosIndexRouteImport.update({
  id: '/eventos/',
  path: '/eventos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const InscripcionEventIdRoute = InscripcionEventIdRouteImport.update({
  id: '/inscripcion/$eventId',
  path: '/inscripcion/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosSlugRoute = EventosSlugRouteImport.update({
  id: '/eventos/$slug',
  path: '/eventos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmacionRegistrationIdRoute =
  ConfirmacionRegistrationIdRouteImport.update({
    id: '/confirmacion/$registrationId',
    path: '/confirmacion/$registrationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CheckoutOrderIdRoute = CheckoutOrderIdRouteImport.update({
  id: '/checkout/$orderId',
  path: '/checkout/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegistroRoute = AuthRegistroRouteImport.update({
  id: '/auth/registro',
  path: '/auth/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRecuperarRoute = AuthRecuperarRouteImport.update({
  id: '/auth/recuperar',
  path: '/auth/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recuperar': typeof AuthRecuperarRoute
  '/auth/registro': typeof AuthRegistroRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/confirmacion/$registrationId': typeof ConfirmacionRegistrationIdRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/inscripcion/$eventId': typeof InscripcionEventIdRoute
  '/admin/': typeof AdminIndexRoute
  '/eventos/': typeof EventosIndexRoute
  '/mi-perfil/': typeof MiPerfilIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recuperar': typeof AuthRecuperarRoute
  '/auth/registro': typeof AuthRegistroRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/confirmacion/$registrationId': typeof ConfirmacionRegistrationIdRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/inscripcion/$eventId': typeof InscripcionEventIdRoute
  '/admin': typeof AdminIndexRoute
  '/eventos': typeof EventosIndexRoute
  '/mi-perfil': typeof MiPerfilIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/recuperar': typeof AuthRecuperarRoute
  '/auth/registro': typeof AuthRegistroRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/confirmacion/$registrationId': typeof ConfirmacionRegistrationIdRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/inscripcion/$eventId': typeof InscripcionEventIdRoute
  '/admin/': typeof AdminIndexRoute
  '/eventos/': typeof EventosIndexRoute
  '/mi-perfil/': typeof MiPerfilIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/recuperar'
    | '/auth/registro'
    | '/checkout/$orderId'
    | '/confirmacion/$registrationId'
    | '/eventos/$slug'
    | '/inscripcion/$eventId'
    | '/admin/'
    | '/eventos/'
    | '/mi-perfil/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/recuperar'
    | '/auth/registro'
    | '/checkout/$orderId'
    | '/confirmacion/$registrationId'
    | '/eventos/$slug'
    | '/inscripcion/$eventId'
    | '/admin'
    | '/eventos'
    | '/mi-perfil'
  id:
    | '__root__'
    | '/'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/recuperar'
    | '/auth/registro'
    | '/checkout/$orderId'
    | '/confirmacion/$registrationId'
    | '/eventos/$slug'
    | '/inscripcion/$eventId'
    | '/admin/'
    | '/eventos/'
    | '/mi-perfil/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRecuperarRoute: typeof AuthRecuperarRoute
  AuthRegistroRoute: typeof AuthRegistroRoute
  CheckoutOrderIdRoute: typeof CheckoutOrderIdRoute
  ConfirmacionRegistrationIdRoute: typeof ConfirmacionRegistrationIdRoute
  EventosSlugRoute: typeof EventosSlugRoute
  InscripcionEventIdRoute: typeof InscripcionEventIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  EventosIndexRoute: typeof EventosIndexRoute
  MiPerfilIndexRoute: typeof MiPerfilIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-perfil/': {
      id: '/mi-perfil/'
      path: '/mi-perfil'
      fullPath: '/mi-perfil/'
      preLoaderRoute: typeof MiPerfilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/': {
      id: '/eventos/'
      path: '/eventos'
      fullPath: '/eventos/'
      preLoaderRoute: typeof EventosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscripcion/$eventId': {
      id: '/inscripcion/$eventId'
      path: '/inscripcion/$eventId'
      fullPath: '/inscripcion/$eventId'
      preLoaderRoute: typeof InscripcionEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/$slug': {
      id: '/eventos/$slug'
      path: '/eventos/$slug'
      fullPath: '/eventos/$slug'
      preLoaderRoute: typeof EventosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmacion/$registrationId': {
      id: '/confirmacion/$registrationId'
      path: '/confirmacion/$registrationId'
      fullPath: '/confirmacion/$registrationId'
      preLoaderRoute: typeof ConfirmacionRegistrationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$orderId': {
      id: '/checkout/$orderId'
      path: '/checkout/$orderId'
      fullPath: '/checkout/$orderId'
      preLoaderRoute: typeof CheckoutOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/registro': {
      id: '/auth/registro'
      path: '/auth/registro'
      fullPath: '/auth/registro'
      preLoaderRoute: typeof AuthRegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/recuperar': {
      id: '/auth/recuperar'
      path: '/auth/recuperar'
      fullPath: '/auth/recuperar'
      preLoaderRoute: typeof AuthRecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRecuperarRoute: AuthRecuperarRoute,
  AuthRegistroRoute: AuthRegistroRoute,
  CheckoutOrderIdRoute: CheckoutOrderIdRoute,
  ConfirmacionRegistrationIdRoute: ConfirmacionRegistrationIdRoute,
  EventosSlugRoute: EventosSlugRoute,
  InscripcionEventIdRoute: InscripcionEventIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  EventosIndexRoute: EventosIndexRoute,
  MiPerfilIndexRoute: MiPerfilIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
